name: Deploy Worker
on:
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          secrets: |
            CAPTCHA_PRIV_KEY
          postCommands: |
            echo "running r2 setup"
            wrangler r2 bucket create socks-storage
        env:
            CAPTCHA_PRIV_KEY: ${{ secrets.TURNSTILE_SERVER_KEY }}
